--Se agrega una data incial apra los productos en el sistema, porder tener informacion qeu mostrar


DO $$
DECLARE
v_user_id INT;
BEGIN
SELECT user_id INTO v_user_id
FROM user_management.users
WHERE email = 'juanpablomontoya618@gmail.com';
INSERT INTO product_management.products (product_name, published_time, description, url_product_image, price, brand, enabled, user_id, productcode) VALUES
                                                                                                                                                        ('Samsung Galaxy S24', NOW(), 'El Samsung Galaxy S24 es un teléfono inteligente con una pantalla Dynamic AMOLED 2X de 6.1 pulgadas, cámara de 50 MP, y batería de larga duración. Ideal para quienes buscan un dispositivo potente y elegante para el día a día.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIGfy8wbRGJ6rSepMQ43ilGW1j2vURRZyh_A&s', 899.99, 'Samsung', TRUE, v_user_id, 'ddwsdwdswedsadde41231231'),
                                                                                                                                                        ('Apple iPhone 15 Pro', NOW(), 'El iPhone 15 Pro es el último modelo de Apple, con una pantalla Super Retina XDR, chip A17 Bionic, y un sistema de cámaras mejorado para fotografía profesional. Ideal para los amantes de la tecnología avanzada.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY6sR5BQE7i2DTjIXndqCAStmZI3Z8m5J_Jg&s', 109349.99, 'Apple', TRUE, v_user_id, 'noi2o1i0i0si03sk3s'),
                                                                                                                                                        ('Dell XPS 13', NOW(), 'La Dell XPS 13 es una computadora portátil ultradelgada con pantalla 4K, procesador Intel Core i7, y hasta 16 GB de RAM. Perfecta para profesionales y estudiantes que requieren potencia y portabilidad.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9FFFdsHNRd1xMITxX_1sjUhbvF1HAIxmbZA&s', 12912.99, 'Dell', TRUE, v_user_id, 'kpkp34kp4k3o9d93u9r83nx'),
                                                                                                                                                        ('HP Spectre x360', NOW(), 'La HP Spectre x360 es una laptop convertible con pantalla táctil 4K OLED y batería de larga duración. Ideal para creativos y viajeros, combina elegancia y versatilidad.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaySKputwFXAVkHXHw0Gn-gtXN5nc1GIV1rA&s', 14929.99, 'HP', TRUE, v_user_id, 'mo1i2o1i2jxu9d93'),
                                                                                                                                                        ('Sony PlayStation 5', NOW(), 'La PlayStation 5 de Sony ofrece una experiencia de juego sin igual, con gráficos 4K, tiempos de carga ultra rápidos, y un control DualSense innovador. Ideal para jugadores exigentes.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrVIGvlSXIWZ3YiPRpVOtK28Api1aUYees6w&s', 4929.99, 'Sony', TRUE, v_user_id, 'sk2opie03i49390id3'),
                                                                                                                                                        ('Apple MacBook Air M2', NOW(), 'El MacBook Air con chip M2 es ideal para quienes buscan un rendimiento rápido y eficiente en un diseño delgado y ligero. Con pantalla Retina, hasta 16 GB de RAM y 256 GB de almacenamiento SSD.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3iYdvxbKa8XdIrqTMeGwMt6A0R6TbaFqyMg&s', 11299.99, 'Apple', TRUE, v_user_id, 'mlm23o1k2o121'),
                                                                                                                                                        ('Garmin Fenix 7', NOW(), 'El Garmin Fenix 7 es un reloj inteligente diseñado para deportistas. Con GPS, monitor de frecuencia cardíaca, y más de 40 modos deportivos, es perfecto para entrenamientos al aire libre.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHwRnXHQzTx3buEFTsCIz3Uz_rKBrO36Jo3w&s', 6419.99, 'Garmin', TRUE, v_user_id, 'sdm3o4k3o4ko31212'),
                                                                                                                                                        ('Casio G-Shock GA-2100', NOW(), 'El Casio G-Shock GA-2100 es un reloj resistente a golpes, con diseño moderno y características como resistencia al agua y múltiples funciones de cronómetro y alarma. Ideal para aventuras extremas.', 'https://www.casio.com/content/dam/casio/product-info/locales/mx/es-ar/timepiece/product/watch/G/GA/GA2/GA-2100-1A1/assets/GA-2100-1A1_Seq04.jpg.transform/main-visual-sp/image.jpg', 99.99, 'Casio', TRUE, v_user_id, 'ej3ei39ei3ei3e3e3'),
                                                                                                                                                        ('Samsung Galaxy Watch 6', NOW(), 'El Galaxy Watch 6 es un reloj inteligente con monitor de salud, GPS y funciones avanzadas para seguimiento de actividad física. Compatible con dispositivos Android e iOS.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf_yPoBwKFs_X56v3L_qAff-7qlyI8uNX0CA&s', 29922.99, 'Samsung', TRUE, v_user_id, '32oed3d3e3'),
                                                                                                                                                        ('Huawei MatePad Pro', NOW(), 'El Huawei MatePad Pro es una tablet Android con pantalla de 10.8 pulgadas, procesador Kirin 990 y soporte para el lápiz óptico M-Pencil. Perfecta para la productividad y el entretenimiento.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk4NPom7Dh8sNaApPAVcKAobsj9e8HiqrlKQ&s', 49911.99, 'Huawei', TRUE, v_user_id, 'm32oie392ie093');
END $$;
